INSERT INTO likes VALUES ('heaven_Taewoo248', 'Ooh La-La!', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('heaven_Taewoo248', 'Merry-Go-Round', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('heaven_Taewoo248', 'Into the New World', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('heaven_Taewoo248', 'I Got a Boy', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('heaven_Taewoo248', 'Express 999', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('heaven_Taewoo248', 'Telepathy', 'The Boys', 'Girls'' Generation');
INSERT INTO likes VALUES ('heaven_Taewoo248', 'How Great Is Your Love', 'The Boys', 'Girls'' Generation');
INSERT INTO likes VALUES ('heaven_Taewoo248', 'Gangnam Style', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('heaven_Taewoo248', 'What Would Have Been?', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('heaven_Taewoo248', 'Coup D''Etat', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('heaven_Taewoo248', 'MichiGO', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('heaven_Taewoo248', 'Black', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('heaven_Taewoo248', 'Devil', 'Devil', 'Super Junior');
INSERT INTO likes VALUES ('heaven_Taewoo248', 'Simply Beautiful', 'Devil', 'Super Junior');
INSERT INTO likes VALUES ('heaven_Taewoo248', 'Toy', 'Blooming Period', 'Block B');
INSERT INTO likes VALUES ('heaven_Taewoo248', 'Talk Love', 'Descendants of the Sun', 'K.Will');
INSERT INTO likes VALUES ('heaven_Taewoo248', 'This Love', 'Amaranth', 'Davichi');
INSERT INTO likes VALUES ('heaven_Taewoo248', 'You''re So Fine', 'BLUEMING', 'CNBLUE');
INSERT INTO likes VALUES ('yichen', 'Baby Baby', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('yichen', 'Promise', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('yichen', 'Express 999', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('yichen', 'Lost In Love', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('yichen', 'Romantic St.', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('yichen', 'Telepathy', 'The Boys', 'Girls'' Generation');
INSERT INTO likes VALUES ('yichen', 'Blue/Tree Frog', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('yichen', 'Gangnam Style', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('yichen', 'Year of 77', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('yichen', 'What Would Have Been?', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('yichen', 'Coup D''Etat', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('yichen', 'MichiGO', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('yichen', 'Niliria', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('yichen', 'R.O.D.', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('yichen', 'Black', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('yichen', 'Who You?', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('yichen', 'Shake the World', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('yichen', 'Crooked', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('yichen', 'Talk Love', 'Descendants of the Sun', 'K.Will');
INSERT INTO likes VALUES ('fish_yeon605', 'Complete', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('fish_yeon605', 'Kissing You', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('fish_yeon605', 'Into the New World', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('fish_yeon605', 'I Got a Boy', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('fish_yeon605', 'Trick', 'The Boys', 'Girls'' Generation');
INSERT INTO likes VALUES ('fish_yeon605', 'Gangnam Style', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('fish_yeon605', 'Year of 77', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('fish_yeon605', 'Shake the World', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('fish_yeon605', 'Crooked', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('fish_yeon605', 'Mr. Taxi', 'Girls'' Generation (Japanese)', 'Girls'' Generation');
INSERT INTO likes VALUES ('fish_yeon605', 'This Love', 'Amaranth', 'Davichi');
INSERT INTO likes VALUES ('fish_yeon605', 'You''re the Best', 'Melting', 'Mamamoo');
INSERT INTO likes VALUES ('fish_yeon605', 'You''re So Fine', 'BLUEMING', 'CNBLUE');
INSERT INTO likes VALUES ('salad_sooyeon402', 'Girls'' Generation', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('salad_sooyeon402', 'Kissing You', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('salad_sooyeon402', 'Into the New World', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('salad_sooyeon402', 'Baby Maybe', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('salad_sooyeon402', 'Talk Talk', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('salad_sooyeon402', 'Promise', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('salad_sooyeon402', 'Express 999', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('salad_sooyeon402', 'Look at Me', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('salad_sooyeon402', 'Romantic St.', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('salad_sooyeon402', 'How Great Is Your Love', 'The Boys', 'Girls'' Generation');
INSERT INTO likes VALUES ('salad_sooyeon402', 'Blue/Tree Frog', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('salad_sooyeon402', 'Passionate Goodbye', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('salad_sooyeon402', 'Gangnam Style', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('salad_sooyeon402', 'R.O.D.', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('salad_sooyeon402', 'Shake the World', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('salad_sooyeon402', 'Devil', 'Devil', 'Super Junior');
INSERT INTO likes VALUES ('salad_sooyeon402', 'Simply Beautiful', 'Devil', 'Super Junior');
INSERT INTO likes VALUES ('salad_sooyeon402', 'Turtle', 'Mystic Ballad', 'Davichi');
INSERT INTO likes VALUES ('salad_sooyeon402', 'Talk Love', 'Descendants of the Sun', 'K.Will');
INSERT INTO likes VALUES ('salad_sooyeon402', 'This Love', 'Amaranth', 'Davichi');
INSERT INTO likes VALUES ('snowflake320', 'Girls'' Generation', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('snowflake320', 'Baby Baby', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('snowflake320', 'Baby Maybe', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('snowflake320', 'Look at Me', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('snowflake320', 'The Boys', 'The Boys', 'Girls'' Generation');
INSERT INTO likes VALUES ('snowflake320', 'Say Yes', 'The Boys', 'Girls'' Generation');
INSERT INTO likes VALUES ('snowflake320', 'How Great Is Your Love', 'The Boys', 'Girls'' Generation');
INSERT INTO likes VALUES ('snowflake320', 'The Boys (English)', 'The Boys', 'Girls'' Generation');
INSERT INTO likes VALUES ('snowflake320', 'Mr. Taxi (Korean)', 'The Boys', 'Girls'' Generation');
INSERT INTO likes VALUES ('snowflake320', 'Blue/Tree Frog', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('snowflake320', 'Gangnam Style', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('snowflake320', 'Coup D''Etat', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('snowflake320', 'Niliria', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('snowflake320', 'R.O.D.', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('snowflake320', 'Run Devil Run', 'Girls'' Generation (Japanese)', 'Girls'' Generation');
INSERT INTO likes VALUES ('annie', 'Lost In Love', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('annie', 'How Great Is Your Love', 'The Boys', 'Girls'' Generation');
INSERT INTO likes VALUES ('annie', 'Blue/Tree Frog', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('annie', 'Gangnam Style', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('annie', 'Year of 77', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('annie', 'R.O.D.', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('annie', 'Black', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('annie', 'Shake the World', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('annie', 'Simply Beautiful', 'Devil', 'Super Junior');
INSERT INTO likes VALUES ('annie', 'Turtle', 'Mystic Ballad', 'Davichi');
INSERT INTO likes VALUES ('luhanlove3', 'Complete', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('luhanlove3', 'Kissing You', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('luhanlove3', 'I Got a Boy', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('luhanlove3', 'Lost In Love', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('luhanlove3', 'The Boys (English)', 'The Boys', 'Girls'' Generation');
INSERT INTO likes VALUES ('luhanlove3', 'Gangnam Style', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('luhanlove3', 'Year of 77', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('luhanlove3', 'Niliria', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('luhanlove3', 'R.O.D.', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('luhanlove3', 'Shake the World', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('luhanlove3', 'Mr. Taxi', 'Girls'' Generation (Japanese)', 'Girls'' Generation');
INSERT INTO likes VALUES ('luhanlove3', 'Run Devil Run', 'Girls'' Generation (Japanese)', 'Girls'' Generation');
INSERT INTO likes VALUES ('luhanlove3', 'Devil', 'Devil', 'Super Junior');
INSERT INTO likes VALUES ('luhanlove3', 'Toy', 'Blooming Period', 'Block B');
INSERT INTO likes VALUES ('luhanlove3', 'This Love', 'Amaranth', 'Davichi');
INSERT INTO likes VALUES ('luhanlove3', 'You''re the Best', 'Melting', 'Mamamoo');
INSERT INTO likes VALUES ('winnielouu', 'Merry-Go-Round', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('winnielouu', 'I Got a Boy', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('winnielouu', 'Baby Maybe', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('winnielouu', 'Talk Talk', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('winnielouu', 'Gangnam Style', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('winnielouu', 'What Would Have Been?', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('winnielouu', 'Who You?', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('winnielouu', 'Crooked', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('winnielouu', 'Devil', 'Devil', 'Super Junior');
INSERT INTO likes VALUES ('winnielouu', 'Simply Beautiful', 'Devil', 'Super Junior');
INSERT INTO likes VALUES ('winnielouu', 'Turtle', 'Mystic Ballad', 'Davichi');
INSERT INTO likes VALUES ('winnielouu', 'This Love', 'Amaranth', 'Davichi');
INSERT INTO likes VALUES ('Emma233', 'Kissing You', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('Emma233', 'Into the New World', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('Emma233', 'I Got a Boy', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('Emma233', 'Baby Maybe', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('Emma233', 'Look at Me', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('Emma233', 'The Boys (English)', 'The Boys', 'Girls'' Generation');
INSERT INTO likes VALUES ('Emma233', 'Gangnam Style', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('Emma233', 'Never Say Goodbye', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('Emma233', 'Coup D''Etat', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('Emma233', 'Black', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('Emma233', 'Shake the World', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('Emma233', 'Mr. Taxi', 'Girls'' Generation (Japanese)', 'Girls'' Generation');
INSERT INTO likes VALUES ('Emma233', 'You-aholic', 'Girls'' Generation (Japanese)', 'Girls'' Generation');
INSERT INTO likes VALUES ('Emma233', 'Turtle', 'Mystic Ballad', 'Davichi');
INSERT INTO likes VALUES ('Emma233', 'Talk Love', 'Descendants of the Sun', 'K.Will');
INSERT INTO likes VALUES ('Emma233', 'You''re the Best', 'Melting', 'Mamamoo');
INSERT INTO likes VALUES ('Davi89', 'Girls'' Generation', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('Davi89', 'Baby Baby', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('Davi89', 'Ooh La-La!', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('Davi89', 'Merry-Go-Round', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('Davi89', 'I Got a Boy', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('Davi89', 'Express 999', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('Davi89', 'Lost In Love', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('Davi89', 'XYZ', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('Davi89', 'The Boys', 'The Boys', 'Girls'' Generation');
INSERT INTO likes VALUES ('Davi89', 'How Great Is Your Love', 'The Boys', 'Girls'' Generation');
INSERT INTO likes VALUES ('Davi89', 'Gangnam Style', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('Davi89', 'Year of 77', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('Davi89', 'Never Say Goodbye', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('Davi89', 'Black', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('Davi89', 'You-aholic', 'Girls'' Generation (Japanese)', 'Girls'' Generation');
INSERT INTO likes VALUES ('Davi89', 'Simply Beautiful', 'Devil', 'Super Junior');
INSERT INTO likes VALUES ('Davi89', 'You''re the Best', 'Melting', 'Mamamoo');
INSERT INTO likes VALUES ('Ian', 'Girls'' Generation', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('Ian', 'Baby Baby', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('Ian', 'Talk Talk', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('Ian', 'Express 999', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('Ian', 'Lost In Love', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('Ian', 'Say Yes', 'The Boys', 'Girls'' Generation');
INSERT INTO likes VALUES ('Ian', 'The Boys (English)', 'The Boys', 'Girls'' Generation');
INSERT INTO likes VALUES ('Ian', 'Passionate Goodbye', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('Ian', 'Gangnam Style', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('Ian', 'What Would Have Been?', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('Ian', 'Never Say Goodbye', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('Ian', 'R.O.D.', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('Ian', 'Mr. Taxi', 'Girls'' Generation (Japanese)', 'Girls'' Generation');
INSERT INTO likes VALUES ('Ian', 'Run Devil Run', 'Girls'' Generation (Japanese)', 'Girls'' Generation');
INSERT INTO likes VALUES ('Ian', 'You-aholic', 'Girls'' Generation (Japanese)', 'Girls'' Generation');
INSERT INTO likes VALUES ('Fred Durst', 'Girls'' Generation', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('Fred Durst', 'Complete', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('Fred Durst', 'Ooh La-La!', 'Girls'' Generation', 'Girls'' Generation');
INSERT INTO likes VALUES ('Fred Durst', 'Romantic St.', 'I Got a Boy', 'Girls'' Generation');
INSERT INTO likes VALUES ('Fred Durst', 'The Boys (English)', 'The Boys', 'Girls'' Generation');
INSERT INTO likes VALUES ('Fred Durst', 'Blue/Tree Frog', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('Fred Durst', 'Gangnam Style', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('Fred Durst', 'Year of 77', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('Fred Durst', 'What Would Have Been?', 'Psy 6 (Six Rules), Part 1', 'PSY');
INSERT INTO likes VALUES ('Fred Durst', 'Shake the World', 'Coup D''Etat', 'G-Dragon');
INSERT INTO likes VALUES ('Fred Durst', 'Run Devil Run', 'Girls'' Generation (Japanese)', 'Girls'' Generation');
INSERT INTO likes VALUES ('Fred Durst', 'Turtle', 'Mystic Ballad', 'Davichi');
INSERT INTO likes VALUES ('Fred Durst', 'Toy', 'Blooming Period', 'Block B');
INSERT INTO likes VALUES ('Fred Durst', 'You''re the Best', 'Melting', 'Mamamoo');
